# Generated by Django 5.2.5 on 2026-02-20 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admit_stds', '0002_admittedstudent_semester'),
        ('exam_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit_stds.admittedstudent')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_schedule.exam')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.hall')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('exam', 'hall', 'row', 'column')},
            },
        ),
    ]
