# Generated by Django 5.2.5 on 2025-12-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('exam', models.CharField(blank=True, max_length=200, null=True)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
