# Generated by Django 5.2.5 on 2026-02-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('std_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.CharField(max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='std_account.student')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
    ]
