# Generated by Django 5.2.5 on 2026-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit_stds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedstudent',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
