# Generated by Django 5.2.5 on 2025-12-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('paper_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(default=90)),
                ('hall', models.CharField(blank=True, max_length=50, null=True)),
                ('candidates', models.IntegerField(default=0)),
                ('invigilators', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
