# Generated by Django 5.2.5 on 2025-09-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamChecklist',
        ),
    ]
