# Generated by Django 5.2.5 on 2026-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('BCA', 'Bachelor in Computer Application')], max_length=3),
        ),
    ]
